FROM ubuntu:16.04

WORKDIR /app

COPY . .

ENV API_URL=http://localhost:8000

RUN apt-get update && apt-get install -y curl && \
	curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt install -y nodejs && \
	npm install && \
	node -v && npm -v && \
	npm cache verify && \
	apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/* 

EXPOSE 5000

CMD ["npm", "start"]