version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=usr123
      - POSTGRES_DB=testdb
    expose: 
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: possu

  frontend: 
    image: anniinasalli/frontend-service
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000
    container_name: frontti

  redis-service:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
    container_name: redis

  backend: 
    image: anniinasalli/backend-service
    volumes:
      - ./logs.txt:/logs.txt
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis-service
      - REDIS_PORT=6379
      - DB_PASSWORD=qwerty
      - DB_USERNAME=usr123
      - DB_NAME=testdb
      - DB_HOST=possu
    container_name: bakki
    depends_on:
      - db
      - frontend
      - redis-service

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: load-balancing
    depends_on:
      - backend
      - frontend