version: '3'

services:
  frontend: 
    image: anniinasalli/frontend-service
    build: ./frontend-example-docker
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000
    container_name: frontti

  backend: 
    image: anniinasalli/backend-service
    build: ./backend-example-docker
    volumes:
      - ./logs.txt:/app/logs.txt
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
    container_name: bakki